source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'FlickrEssentials' do
    use_frameworks!
    pod 'CocoaLumberjack'
    pod 'AFNetworking', '~> 3.0'
    pod 'MagicalRecord'
    pod 'RaisinToast'
    pod 'MBProgressHUD', '~> 0.9.2'
end

target 'FlickrEssentialsTests' do
    use_frameworks!
    pod 'KIF', :configurations => ['Debug']
    pod 'KIF/IdentifierTests', :configurations => ['Debug']
end
