# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Settings' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Settings
  pod 'KeychainAccess'
  pod 'Toast-Swift', :git => 'https://github.com/jasonhenderson/Toast-Swift.git'
  pod 'JPSVolumeButtonHandler'

  target 'SettingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
